const Types = {
    INIT_TABLE: 'INIT_TABLE',
    SET_FILTER: 'SET_FILTER',
    FETCH_FILES_START: 'FETCH_FILES_START',
    FETCH_FILES_SUCCESS: 'FETCH_FILES_SUCCESS',
    FETCH_FILES_FAILURE: 'FETCH_FILES_FAILURE',
};

export default Types;
